//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWA.Ariadne.Gui.Dialogs.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SWA.Ariadne.Gui.Dialogs.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap ButtonAbout {
            get {
                object obj = ResourceManager.GetObject("ButtonAbout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----------------------------------------------------------------------
        ///
        ///   ====================
        ///   Feature Log: Ariadne
        ///   ====================
        ///
        ///Copyright (c) Stephan.Wacker@web.de, 2008 - 2009
        ///
        ///-----------------------------------------------------------------------
        ///
        ///Version 3.4
        ///
        /// * added a Heuristic variant to all Flooder solvers
        ///
        ///-----------------------------------------------------------------------
        ///
        ///Version 3.3 -- r314 -- 2009-01-03
        ///
        /// * Screen Saver control: during the first few secon [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FeatureLogTxt {
            get {
                return ResourceManager.GetString("FeatureLogTxt", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ImageStephan_64x64 {
            get {
                object obj = ResourceManager.GetObject("ImageStephan_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Ariadne&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        H1,H2,H3,H4 { font-family:Arial,Helvetica,sans-serif; color:#0F177C; text-decoration:none }
        ///        BODY,P,TABLE,OL,UL,BLOCKQUOTE,DD { font-family:Arial,Helvetica,sans-serif; color:#000000; }
        ///        DT,SPAN.item { font-family:Arial,Helvetica,sans-serif; font-weight:700; font-size:small; color:#000000; }
        ///        DD { margin-b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OverviewHtml {
            get {
                return ResourceManager.GetString("OverviewHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----------------------------------------------------------------------
        ///
        ///   =================
        ///   Overview: Ariadne
        ///   =================
        ///
        ///Copyright (c) Stephan.Wacker@web.de, 2008
        ///
        ///Go to http://www.wacker-muc.de/ for downloading the latest release.
        ///
        ///-----------------------------------------------------------------------
        ///
        ///The Ariadne application builds and solves a variety of maze puzzles.  a) When running as a regular application (Ariadne.exe), you can control the maze layout, its shape, addition [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OverviewTxt {
            get {
                return ResourceManager.GetString("OverviewTxt", resourceCulture);
            }
        }
    }
}
