// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using System.Windows.Forms;
using SWA.Ariadne.Model;
using SWA.Ariadne.Outlines;

namespace SWA.Ariadne.Outlines.Tests
{
    /// <summary>
    ///This is a test class for SWA.Ariadne.Outlines.DistortedOutlineShape and is intended
    ///to contain all SWA.Ariadne.Outlines.DistortedOutlineShape Unit Tests
    ///</summary>
    [TestClass()]
    public class DistortedOutlineShapeTest
    {
        #region Test Context

        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }

        #endregion

        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion

        #region Unit tests

        /// <summary>
        ///A test for DistortedOutlineShape (int, int, SmoothOutlineShape, Distortion)
        ///</summary>
        [DeploymentItem("SWA.Ariadne.Outlines.dll")]
        [TestMethod()]
        public void DOS_ConstructorTest_01()
        {
            int corners = 3, windings = 1;
            double slant = 0, centerX = 0.5, centerY = 0.5, shapeSize = 0.8;
            double distortionWinding = 0.25;

            DistortedPolygonTest(corners, windings, slant, centerX, centerY, shapeSize, distortionWinding);
        }

#if false
        /// <summary>
        ///A test for SpiralDistortion (Random, double, double, double, double)
        ///</summary>
        [DeploymentItem("SWA.Ariadne.Outlines.dll")]
        [TestMethod()]
        public void SpiralDistortionTest()
        {
            Random r = null; // TODO: Initialize to an appropriate value

            double xCenter = 0; // TODO: Initialize to an appropriate value

            double yCenter = 0; // TODO: Initialize to an appropriate value

            double size = 0; // TODO: Initialize to an appropriate value

            double maxWindings = 0; // TODO: Initialize to an appropriate value

            SWA.Ariadne.Outlines.Tests.SWA_Ariadne_Outlines_DistortedOutlineShape_DistortionAccessor expected = null;
            SWA.Ariadne.Outlines.Tests.SWA_Ariadne_Outlines_DistortedOutlineShape_DistortionAccessor actual;

            actual = SWA.Ariadne.Outlines.Tests.SWA_Ariadne_Outlines_DistortedOutlineShapeAccessor.SpiralDistortion(r, xCenter, yCenter, size, maxWindings);

            Assert.AreEqual(expected, actual, "SWA.Ariadne.Outlines.DistortedOutlineShape.SpiralDistortion did not return the ex" +
                    "pected value.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }
#endif

#if false
        /// <summary>
        ///A test for this[double x, double y]
        ///</summary>
        [DeploymentItem("SWA.Ariadne.Outlines.dll")]
        [TestMethod()]
        public void ItemTest()
        {
            int xSize = 0; // TODO: Initialize to an appropriate value

            int ySize = 0; // TODO: Initialize to an appropriate value

            SWA.Ariadne.Outlines.Tests.SWA_Ariadne_Outlines_SmoothOutlineShapeAccessor baseShape = null; // TODO: Initialize to an appropriate value

            SWA.Ariadne.Outlines.Tests.SWA_Ariadne_Outlines_DistortedOutlineShape_DistortionAccessor distortion = null; // TODO: Initialize to an appropriate value

            OutlineShape target = SWA.Ariadne.Outlines.Tests.SWA_Ariadne_Outlines_DistortedOutlineShapeAccessor.CreatePrivate(xSize, ySize, baseShape, distortion);

            bool val = false; // TODO: Assign to an appropriate value for the property

            SWA.Ariadne.Outlines.Tests.SWA_Ariadne_Outlines_DistortedOutlineShapeAccessor accessor = new SWA.Ariadne.Outlines.Tests.SWA_Ariadne_Outlines_DistortedOutlineShapeAccessor(target);

            double x = 0; // TODO: Initialize to an appropriate value

            double y = 0; // TODO: Initialize to an appropriate value


            Assert.AreEqual(val, accessor[x, y], "SWA.Ariadne.Outlines.DistortedOutlineShape.this was not set correctly.");
            Assert.Inconclusive("Verify the correctness of this test method.");
        }
#endif

        #endregion

        #region Auxiliary methods

        private static void DistortedPolygonTest(int corners, int windings, double slant, double centerX, double centerY, double shapeSize, double distortionWinding)
        {
            string testObject = string.Format(
                "DistortedOutlineShape: Polygon({0}) @ ({1:0.##}, {2:0.##}), Spiral({3:0.##})",
                corners, centerX, centerY, distortionWinding);

            MazeTestForm.MazeConfiguratorDelegate mazeConfigurator = DistortedPolygonConfiguratorDelegate(corners, windings, slant, centerX, centerY, shapeSize, distortionWinding);

            MazeTestForm form = new MazeTestForm(mazeConfigurator);
            form.Text = testObject;
            DialogResult result = form.ShowDialog();

            Assert.AreEqual(DialogResult.OK, result, testObject);
        }

        public static MazeTestForm.MazeConfiguratorDelegate DistortedPolygonConfiguratorDelegate(int corners, int windings, double slant, double centerX, double centerY, double shapeSize, double distortionWinding)
        {
            MazeTestForm.MazeConfiguratorDelegate mazeConfigurator = delegate(Maze maze)
            {
                int xSize = maze.XSize, ySize = maze.YSize;
                OutlineShape baseShape = SWA_Ariadne_Outlines_PolygonOutlineShapeAccessor.CreatePrivate(corners, windings, slant, xSize, ySize, centerX, centerY, shapeSize);

                SWA_Ariadne_Outlines_SmoothOutlineShapeAccessor baseShapeAccessor = new SWA_Ariadne_Outlines_SmoothOutlineShapeAccessor(baseShape);

                double xCenter, yCenter, size;
                SWA_Ariadne_Outlines_OutlineShapeAccessor.ConvertParameters(xSize, ySize, centerX, centerY, shapeSize, out xCenter, out yCenter, out size);
                SWA_Ariadne_Outlines_DistortedOutlineShape_DistortionAccessor distortion = SWA_Ariadne_Outlines_DistortedOutlineShapeAccessor.SpiralDistortion(xCenter, yCenter, size, distortionWinding);

                OutlineShape targetShape = SWA_Ariadne_Outlines_DistortedOutlineShapeAccessor.CreatePrivate(xSize, ySize, baseShapeAccessor, distortion);

                maze.OutlineShape = targetShape;
            };
            return mazeConfigurator;
        }

        #endregion
    }
}
