// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using System.Windows.Forms;
using SWA.Ariadne.Outlines;

namespace SWA.Ariadne.Outlines.Tests
{
    /// <summary>
    ///This is a test class for SWA.Ariadne.Outlines.PolygonOutlineShape and is intended
    ///to contain all SWA.Ariadne.Outlines.PolygonOutlineShape Unit Tests
    ///</summary>
    [TestClass()]
    public class PolygonOutlineShapeTest
    {
        #region Test Context

        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }

        #endregion

        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion

        #region Unit Tests

        /// <summary>
        ///A test for PolygonOutlineShape (int, int, double, int, int, double, double, double)
        ///</summary>
        [TestMethod()]
        public void POS_ManualTest_01()
        {
            string testObject = "PolygonOutlineShape";

            MazeTestForm form = new PolygonTestForm();
            form.Text = testObject;
            DialogResult result = form.ShowDialog();

            Assert.AreEqual(DialogResult.OK, result, testObject);
        }

        #endregion
    }
}
