// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using System.Drawing;
using SWA.Ariadne.Settings;

namespace SWA.Ariadne.Gui.Tests
{
    /// <summary>
    ///This is a test class for SWA.Ariadne.Gui.Mazes.ImageLoader and is intended
    ///to contain all SWA.Ariadne.Gui.Mazes.ImageLoader Unit Tests
    ///</summary>
    [TestClass()]
    public class ImageLoaderTest
    {
        #region Test Context

        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }

        #endregion

        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion

        #region Unit tests

        /// <summary>
        ///A test for GetNext ()
        ///</summary>
        [DeploymentItem("SWA.Ariadne.Gui.Mazes.dll")]
        [TestMethod()]
        public void IL_GetNextTest_01()
        {
            string testObject = "GetNext";

            int minSize = 300;
            int maxSize = 500;
            string imageFolder = RegisteredOptions.GetStringSetting(RegisteredOptions.OPT_IMAGE_FOLDER);

            int queueLength = 4;

            object target = SWA_Ariadne_Gui_Mazes_ImageLoaderAccessor.CreatePrivate(minSize, maxSize, imageFolder, queueLength);
            SWA_Ariadne_Gui_Mazes_ImageLoaderAccessor accessor = new SWA_Ariadne_Gui_Mazes_ImageLoaderAccessor(target);

            for (int i = 0; i < 20; i++)
            {
                Image img = accessor.GetNext();
                Assert.AreNotEqual(null, img, testObject + "returned null");
            }
        }

        #endregion
    }
}
