// ------------------------------------------------------------------------------
//<autogenerated>
//        This code was generated by Microsoft Visual Studio Team System 2005.
//
//        Changes to this file may cause incorrect behavior and will be lost if
//        the code is regenerated.
//</autogenerated>
//------------------------------------------------------------------------------
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace SWA.Ariadne.Gui.Tests
{
[System.Diagnostics.DebuggerStepThrough()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
internal class BaseAccessor {
    
    protected Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject m_privateObject;
    
    protected BaseAccessor(object target, Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType type) {
        m_privateObject = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateObject(target, type);
    }
    
    protected BaseAccessor(Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType type) : 
            this(null, type) {
    }
    
    internal virtual object Target {
        get {
            return m_privateObject.Target;
        }
    }
    
    public override string ToString() {
        return this.Target.ToString();
    }
    
    public override bool Equals(object obj) {
        if (typeof(BaseAccessor).IsInstanceOfType(obj)) {
            obj = ((BaseAccessor)(obj)).Target;
        }
        return this.Target.Equals(obj);
    }
    
    public override int GetHashCode() {
        return this.Target.GetHashCode();
    }
}
[System.Diagnostics.DebuggerStepThrough()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TestTools.UnitTestGeneration", "1.0.0.0")]
internal class SWA_Ariadne_Gui_OptionsDialogAccessor : BaseAccessor {
    
    protected static Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType m_privateType = new Microsoft.VisualStudio.TestTools.UnitTesting.PrivateType(typeof(global::SWA.Ariadne.Gui.Dialogs.OptionsDialog));
    
    internal SWA_Ariadne_Gui_OptionsDialogAccessor(global::SWA.Ariadne.Gui.Dialogs.OptionsDialog target) : 
            base(target, m_privateType) {
    }
    
    internal global::System.ComponentModel.IContainer components {
        get {
            global::System.ComponentModel.IContainer ret = ((global::System.ComponentModel.IContainer)(m_privateObject.GetField("components")));
            return ret;
        }
        set {
            m_privateObject.SetField("components", value);
        }
    }
    
    internal global::System.Windows.Forms.Button buttonOK {
        get {
            global::System.Windows.Forms.Button ret = ((global::System.Windows.Forms.Button)(m_privateObject.GetField("buttonOK")));
            return ret;
        }
        set {
            m_privateObject.SetField("buttonOK", value);
        }
    }
    
    internal global::System.Windows.Forms.Button buttonCancel {
        get {
            global::System.Windows.Forms.Button ret = ((global::System.Windows.Forms.Button)(m_privateObject.GetField("buttonCancel")));
            return ret;
        }
        set {
            m_privateObject.SetField("buttonCancel", value);
        }
    }
    
    internal global::System.Windows.Forms.Label labelCopyright {
        get {
            global::System.Windows.Forms.Label ret = ((global::System.Windows.Forms.Label)(m_privateObject.GetField("labelCopyright")));
            return ret;
        }
        set {
            m_privateObject.SetField("labelCopyright", value);
        }
    }
    
    internal global::System.Windows.Forms.TabControl tabControl1 {
        get {
            global::System.Windows.Forms.TabControl ret = ((global::System.Windows.Forms.TabControl)(m_privateObject.GetField("tabControl1")));
            return ret;
        }
        set {
            m_privateObject.SetField("tabControl1", value);
        }
    }
    
    internal global::System.Windows.Forms.TabPage tabPage1 {
        get {
            global::System.Windows.Forms.TabPage ret = ((global::System.Windows.Forms.TabPage)(m_privateObject.GetField("tabPage1")));
            return ret;
        }
        set {
            m_privateObject.SetField("tabPage1", value);
        }
    }
    
    internal global::System.Windows.Forms.CheckBox checkBoxEfficientSolvers {
        get {
            global::System.Windows.Forms.CheckBox ret = ((global::System.Windows.Forms.CheckBox)(m_privateObject.GetField("checkBoxEfficientSolvers")));
            return ret;
        }
        set {
            m_privateObject.SetField("checkBoxEfficientSolvers", value);
        }
    }
    
    internal global::System.Windows.Forms.TextBox textBoxStepsPerSecond {
        get {
            global::System.Windows.Forms.TextBox ret = ((global::System.Windows.Forms.TextBox)(m_privateObject.GetField("textBoxStepsPerSecond")));
            return ret;
        }
        set {
            m_privateObject.SetField("textBoxStepsPerSecond", value);
        }
    }
    
    internal global::System.Windows.Forms.Label label1 {
        get {
            global::System.Windows.Forms.Label ret = ((global::System.Windows.Forms.Label)(m_privateObject.GetField("label1")));
            return ret;
        }
        set {
            m_privateObject.SetField("label1", value);
        }
    }
    
    internal global::System.Windows.Forms.CheckBox checkBoxDetailsBox {
        get {
            global::System.Windows.Forms.CheckBox ret = ((global::System.Windows.Forms.CheckBox)(m_privateObject.GetField("checkBoxDetailsBox")));
            return ret;
        }
        set {
            m_privateObject.SetField("checkBoxDetailsBox", value);
        }
    }
    
    internal global::System.Windows.Forms.CheckBox checkBoxBlinking {
        get {
            global::System.Windows.Forms.CheckBox ret = ((global::System.Windows.Forms.CheckBox)(m_privateObject.GetField("checkBoxBlinking")));
            return ret;
        }
        set {
            m_privateObject.SetField("checkBoxBlinking", value);
        }
    }
    
    internal global::System.Windows.Forms.TabPage tabPage2 {
        get {
            global::System.Windows.Forms.TabPage ret = ((global::System.Windows.Forms.TabPage)(m_privateObject.GetField("tabPage2")));
            return ret;
        }
        set {
            m_privateObject.SetField("tabPage2", value);
        }
    }
    
    internal global::System.Windows.Forms.NumericUpDown imageMinSizeNumericUpDown {
        get {
            global::System.Windows.Forms.NumericUpDown ret = ((global::System.Windows.Forms.NumericUpDown)(m_privateObject.GetField("imageMinSizeNumericUpDown")));
            return ret;
        }
        set {
            m_privateObject.SetField("imageMinSizeNumericUpDown", value);
        }
    }
    
    internal global::System.Windows.Forms.Label labelImagesMinSize {
        get {
            global::System.Windows.Forms.Label ret = ((global::System.Windows.Forms.Label)(m_privateObject.GetField("labelImagesMinSize")));
            return ret;
        }
        set {
            m_privateObject.SetField("labelImagesMinSize", value);
        }
    }
    
    internal global::System.Windows.Forms.NumericUpDown imageMaxSizeNumericUpDown {
        get {
            global::System.Windows.Forms.NumericUpDown ret = ((global::System.Windows.Forms.NumericUpDown)(m_privateObject.GetField("imageMaxSizeNumericUpDown")));
            return ret;
        }
        set {
            m_privateObject.SetField("imageMaxSizeNumericUpDown", value);
        }
    }
    
    internal global::System.Windows.Forms.Label labelImagesMaxSize {
        get {
            global::System.Windows.Forms.Label ret = ((global::System.Windows.Forms.Label)(m_privateObject.GetField("labelImagesMaxSize")));
            return ret;
        }
        set {
            m_privateObject.SetField("labelImagesMaxSize", value);
        }
    }
    
    internal global::System.Windows.Forms.NumericUpDown imageNumberNumericUpDown {
        get {
            global::System.Windows.Forms.NumericUpDown ret = ((global::System.Windows.Forms.NumericUpDown)(m_privateObject.GetField("imageNumberNumericUpDown")));
            return ret;
        }
        set {
            m_privateObject.SetField("imageNumberNumericUpDown", value);
        }
    }
    
    internal global::System.Windows.Forms.Label labelImagesNumber {
        get {
            global::System.Windows.Forms.Label ret = ((global::System.Windows.Forms.Label)(m_privateObject.GetField("labelImagesNumber")));
            return ret;
        }
        set {
            m_privateObject.SetField("labelImagesNumber", value);
        }
    }
    
    internal global::System.Windows.Forms.Button selectImageFolderButton {
        get {
            global::System.Windows.Forms.Button ret = ((global::System.Windows.Forms.Button)(m_privateObject.GetField("selectImageFolderButton")));
            return ret;
        }
        set {
            m_privateObject.SetField("selectImageFolderButton", value);
        }
    }
    
    internal global::System.Windows.Forms.TextBox imageFolderTextBox {
        get {
            global::System.Windows.Forms.TextBox ret = ((global::System.Windows.Forms.TextBox)(m_privateObject.GetField("imageFolderTextBox")));
            return ret;
        }
        set {
            m_privateObject.SetField("imageFolderTextBox", value);
        }
    }
    
    internal global::System.Windows.Forms.FolderBrowserDialog imageFolderBrowserDialog {
        get {
            global::System.Windows.Forms.FolderBrowserDialog ret = ((global::System.Windows.Forms.FolderBrowserDialog)(m_privateObject.GetField("imageFolderBrowserDialog")));
            return ret;
        }
        set {
            m_privateObject.SetField("imageFolderBrowserDialog", value);
        }
    }
    
    internal global::System.Windows.Forms.TabPage tabPage3 {
        get {
            global::System.Windows.Forms.TabPage ret = ((global::System.Windows.Forms.TabPage)(m_privateObject.GetField("tabPage3")));
            return ret;
        }
        set {
            m_privateObject.SetField("tabPage3", value);
        }
    }
    
    internal global::System.Windows.Forms.CheckBox checkBoxOutlineShapes {
        get {
            global::System.Windows.Forms.CheckBox ret = ((global::System.Windows.Forms.CheckBox)(m_privateObject.GetField("checkBoxOutlineShapes")));
            return ret;
        }
        set {
            m_privateObject.SetField("checkBoxOutlineShapes", value);
        }
    }
    
    internal void OptionsDialog_Load(object sender, global::System.EventArgs e) {
        object[] args = new object[] {
                sender,
                e};
        m_privateObject.Invoke("OptionsDialog_Load", new System.Type[] {
                    typeof(object),
                    typeof(global::System.EventArgs)}, args);
    }
    
    internal void buttonOK_Click(object sender, global::System.EventArgs e) {
        object[] args = new object[] {
                sender,
                e};
        m_privateObject.Invoke("buttonOK_Click", new System.Type[] {
                    typeof(object),
                    typeof(global::System.EventArgs)}, args);
    }
    
    internal void buttonCancel_Click(object sender, global::System.EventArgs e) {
        object[] args = new object[] {
                sender,
                e};
        m_privateObject.Invoke("buttonCancel_Click", new System.Type[] {
                    typeof(object),
                    typeof(global::System.EventArgs)}, args);
    }
    
    internal void selectImageFolderButton_Click(object sender, global::System.EventArgs e) {
        object[] args = new object[] {
                sender,
                e};
        m_privateObject.Invoke("selectImageFolderButton_Click", new System.Type[] {
                    typeof(object),
                    typeof(global::System.EventArgs)}, args);
    }
    
    internal void LoadSettings() {
        object[] args = new object[0];
        m_privateObject.Invoke("LoadSettings", new System.Type[0], args);
    }
    
    internal void SaveSettings() {
        object[] args = new object[0];
        m_privateObject.Invoke("SaveSettings", new System.Type[0], args);
    }
    
    internal void Dispose(bool disposing) {
        object[] args = new object[] {
                disposing};
        m_privateObject.Invoke("Dispose", new System.Type[] {
                    typeof(bool)}, args);
    }
    
    internal void InitializeComponent() {
        object[] args = new object[0];
        m_privateObject.Invoke("InitializeComponent", new System.Type[0], args);
    }
}
}
