//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWA.Ariadne.Outlines.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Bitmaps {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Bitmaps() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SWA.Ariadne.Outlines.Resources.Bitmaps", typeof(Bitmaps).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Achtung {
            get {
                object obj = ResourceManager.GetObject("Achtung", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Africa {
            get {
                object obj = ResourceManager.GetObject("Africa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Antarctica {
            get {
                object obj = ResourceManager.GetObject("Antarctica", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Australia {
            get {
                object obj = ResourceManager.GetObject("Australia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Austria {
            get {
                object obj = ResourceManager.GetObject("Austria", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bat_02 {
            get {
                object obj = ResourceManager.GetObject("Bat_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bavaria {
            get {
                object obj = ResourceManager.GetObject("Bavaria", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bishop {
            get {
                object obj = ResourceManager.GetObject("Bishop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BritishIslands {
            get {
                object obj = ResourceManager.GetObject("BritishIslands", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Butterfly_01 {
            get {
                object obj = ResourceManager.GetObject("Butterfly_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Butterfly_02 {
            get {
                object obj = ResourceManager.GetObject("Butterfly_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Camel_01 {
            get {
                object obj = ResourceManager.GetObject("Camel_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Camel_02 {
            get {
                object obj = ResourceManager.GetObject("Camel_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Canguru_01 {
            get {
                object obj = ResourceManager.GetObject("Canguru_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cat_01 {
            get {
                object obj = ResourceManager.GetObject("Cat_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cat_02 {
            get {
                object obj = ResourceManager.GetObject("Cat_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap China {
            get {
                object obj = ResourceManager.GetObject("China", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Corsica {
            get {
                object obj = ResourceManager.GetObject("Corsica", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cow_01 {
            get {
                object obj = ResourceManager.GetObject("Cow_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cyprus {
            get {
                object obj = ResourceManager.GetObject("Cyprus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CzechRepublic {
            get {
                object obj = ResourceManager.GetObject("CzechRepublic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Delphin_01 {
            get {
                object obj = ResourceManager.GetObject("Delphin_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dog_01 {
            get {
                object obj = ResourceManager.GetObject("Dog_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dog_02 {
            get {
                object obj = ResourceManager.GetObject("Dog_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dog_03 {
            get {
                object obj = ResourceManager.GetObject("Dog_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Doppelkurve {
            get {
                object obj = ResourceManager.GetObject("Doppelkurve", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Duck_01 {
            get {
                object obj = ResourceManager.GetObject("Duck_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Eagle_01 {
            get {
                object obj = ResourceManager.GetObject("Eagle_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EinfahrtVerboten {
            get {
                object obj = ResourceManager.GetObject("EinfahrtVerboten", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Elephant_01 {
            get {
                object obj = ResourceManager.GetObject("Elephant_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Europe {
            get {
                object obj = ResourceManager.GetObject("Europe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fahrrad {
            get {
                object obj = ResourceManager.GetObject("Fahrrad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fahrradweg {
            get {
                object obj = ResourceManager.GetObject("Fahrradweg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap France {
            get {
                object obj = ResourceManager.GetObject("France", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Frog_01 {
            get {
                object obj = ResourceManager.GetObject("Frog_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Frog_02 {
            get {
                object obj = ResourceManager.GetObject("Frog_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Frog_03 {
            get {
                object obj = ResourceManager.GetObject("Frog_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fussgaenger {
            get {
                object obj = ResourceManager.GetObject("Fussgaenger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fussgaengerueberweg {
            get {
                object obj = ResourceManager.GetObject("Fussgaengerueberweg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Gegenverkehr {
            get {
                object obj = ResourceManager.GetObject("Gegenverkehr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Germany {
            get {
                object obj = ResourceManager.GetObject("Germany", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Greenland {
            get {
                object obj = ResourceManager.GetObject("Greenland", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Halteverbot {
            get {
                object obj = ResourceManager.GetObject("Halteverbot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Hoechstgeschwindigkeit {
            get {
                object obj = ResourceManager.GetObject("Hoechstgeschwindigkeit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Hungary {
            get {
                object obj = ResourceManager.GetObject("Hungary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Iberia {
            get {
                object obj = ResourceManager.GetObject("Iberia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap India {
            get {
                object obj = ResourceManager.GetObject("India", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Interstate {
            get {
                object obj = ResourceManager.GetObject("Interstate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Islandia {
            get {
                object obj = ResourceManager.GetObject("Islandia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Italy {
            get {
                object obj = ResourceManager.GetObject("Italy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ItalyMainland {
            get {
                object obj = ResourceManager.GetObject("ItalyMainland", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Japan {
            get {
                object obj = ResourceManager.GetObject("Japan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KFZ {
            get {
                object obj = ResourceManager.GetObject("KFZ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KFZ_Verbot {
            get {
                object obj = ResourceManager.GetObject("KFZ_Verbot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap King {
            get {
                object obj = ResourceManager.GetObject("King", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Knight {
            get {
                object obj = ResourceManager.GetObject("Knight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Kreisverkehr {
            get {
                object obj = ResourceManager.GetObject("Kreisverkehr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Lizard_01 {
            get {
                object obj = ResourceManager.GetObject("Lizard_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Madagascar {
            get {
                object obj = ResourceManager.GetObject("Madagascar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mexico {
            get {
                object obj = ResourceManager.GetObject("Mexico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Mindestgeschwindigkeit {
            get {
                object obj = ResourceManager.GetObject("Mindestgeschwindigkeit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NorthAmerica {
            get {
                object obj = ResourceManager.GetObject("NorthAmerica", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NumberedRoute {
            get {
                object obj = ResourceManager.GetObject("NumberedRoute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Parkverbot {
            get {
                object obj = ResourceManager.GetObject("Parkverbot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Paw_01 {
            get {
                object obj = ResourceManager.GetObject("Paw_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Paw_02 {
            get {
                object obj = ResourceManager.GetObject("Paw_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pawn {
            get {
                object obj = ResourceManager.GetObject("Pawn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Peru {
            get {
                object obj = ResourceManager.GetObject("Peru", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PKW {
            get {
                object obj = ResourceManager.GetObject("PKW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Poland {
            get {
                object obj = ResourceManager.GetObject("Poland", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Queen {
            get {
                object obj = ResourceManager.GetObject("Queen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rabbit_01 {
            get {
                object obj = ResourceManager.GetObject("Rabbit_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rabbit_02 {
            get {
                object obj = ResourceManager.GetObject("Rabbit_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rabbit_03 {
            get {
                object obj = ResourceManager.GetObject("Rabbit_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Reiter {
            get {
                object obj = ResourceManager.GetObject("Reiter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Restaurant {
            get {
                object obj = ResourceManager.GetObject("Restaurant", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rook {
            get {
                object obj = ResourceManager.GetObject("Rook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Russia {
            get {
                object obj = ResourceManager.GetObject("Russia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Scandinavia {
            get {
                object obj = ResourceManager.GetObject("Scandinavia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shark_01 {
            get {
                object obj = ResourceManager.GetObject("Shark_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shark_02 {
            get {
                object obj = ResourceManager.GetObject("Shark_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sicily {
            get {
                object obj = ResourceManager.GetObject("Sicily", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SkullAndCrossbones {
            get {
                object obj = ResourceManager.GetObject("SkullAndCrossbones", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SouthAmerica {
            get {
                object obj = ResourceManager.GetObject("SouthAmerica", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stamp146x195 {
            get {
                object obj = ResourceManager.GetObject("Stamp146x195", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stamp146x195_Open {
            get {
                object obj = ResourceManager.GetObject("Stamp146x195_Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stamp194x98 {
            get {
                object obj = ResourceManager.GetObject("Stamp194x98", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stamp194x98_Open {
            get {
                object obj = ResourceManager.GetObject("Stamp194x98_Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Texas {
            get {
                object obj = ResourceManager.GetObject("Texas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tibet {
            get {
                object obj = ResourceManager.GetObject("Tibet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap USA {
            get {
                object obj = ResourceManager.GetObject("USA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Vorfahrt {
            get {
                object obj = ResourceManager.GetObject("Vorfahrt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Vorfahrtsstrasse {
            get {
                object obj = ResourceManager.GetObject("Vorfahrtsstrasse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VorsichtFussgaenger {
            get {
                object obj = ResourceManager.GetObject("VorsichtFussgaenger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
