// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using System.Drawing;
using System.Windows.Forms;
using SWA.Ariadne.Gui.Mazes;

namespace SWA.Ariadne.Gui.Tests
{
    /// <summary>
    ///This is a test class for SWA.Ariadne.Gui.Mazes.ContourImage and is intended
    ///to contain all SWA.Ariadne.Gui.Mazes.ContourImage Unit Tests
    ///</summary>
    [TestClass()]
    public class ContourImageTest
    {
        #region Test Context

        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }

        #endregion

        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion

        #region Unit tests

        /// <summary>
        ///A test for CreateFrom (Bitmap, out Bitmap)
        ///</summary>
        [TestMethod()]
        public void CI_ManualTest_01()
        {
            string testObject = "ContourImage";

            TestForm form = new ContourImageTestForm();
            form.Text = testObject;
            DialogResult result = form.ShowDialog();

            Assert.AreEqual(DialogResult.OK, result, testObject);
        }

        #region Unit tests for PrepareInfluenceRegion()

        /// <summary>
        ///A test for PrepareInfluenceRegions (int)
        ///</summary>
        [DeploymentItem("SWA.Ariadne.Gui.Mazes.dll")]
        [TestMethod()]
        public void CI_PrepareInfluenceRegionsTest_01()
        {
            string testObject = "Distance from object pixel";
            int radius = SWA_Ariadne_Gui_Mazes_ContourImageAccessor.ContourDistance;
            int influenceRange = radius + 1;

            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.PrepareInfluenceRegions(influenceRange);

            int dyN = SWA_Ariadne_Gui_Mazes_ContourImageAccessor.NbDY[SWA_Ariadne_Gui_Mazes_ContourImageAccessor.NbN];
            int dyS = -dyN;
            int dxW = SWA_Ariadne_Gui_Mazes_ContourImageAccessor.NbDX[SWA_Ariadne_Gui_Mazes_ContourImageAccessor.NbW];
            int dxE = -dxW;

            int nbL = SWA_Ariadne_Gui_Mazes_ContourImageAccessor.NbW;
            int nbR = SWA_Ariadne_Gui_Mazes_ContourImageAccessor.NbS;

            TestInfluence(testObject, nbL, nbR, radius * dxE, 0, +1);   // E
            TestInfluence(testObject, nbL, nbR, radius * dxE, dyN, +1); // E + 1px N
            TestNoInfluence(testObject, nbL, nbR, radius * dxE, dyS);   // E + 1Px S

            TestInfluence(testObject, nbL, nbR, 0, radius * dyN, 0);    // N
            TestInfluence(testObject, nbL, nbR, dxE, radius * dyN, 0);  // N + 1px E
            TestNoInfluence(testObject, nbL, nbR, dxW, radius * dyN);   // N + 1px W
        }

        /// <summary>
        ///A test for PrepareInfluenceRegions (int)
        ///</summary>
        [DeploymentItem("SWA.Ariadne.Gui.Mazes.dll")]
        [TestMethod()]
        public void CI_PrepareInfluenceRegionsTest_02()
        {
            string testObject = "Distance from object pixel";
            int radius = SWA_Ariadne_Gui_Mazes_ContourImageAccessor.ContourDistance;
            int influenceRange = radius + 1;

            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.PrepareInfluenceRegions(influenceRange);

            int dyN = SWA_Ariadne_Gui_Mazes_ContourImageAccessor.NbDY[SWA_Ariadne_Gui_Mazes_ContourImageAccessor.NbN];
            int dyS = -dyN;
            int dxW = SWA_Ariadne_Gui_Mazes_ContourImageAccessor.NbDX[SWA_Ariadne_Gui_Mazes_ContourImageAccessor.NbW];
            int dxE = -dxW;

            int nbL = SWA_Ariadne_Gui_Mazes_ContourImageAccessor.NbW;
            int nbR = SWA_Ariadne_Gui_Mazes_ContourImageAccessor.NbE;

            TestInfluence(testObject, nbL, nbR, 0, radius * dyN, 0);    // N
            TestNoInfluence(testObject, nbL, nbR, dxW, radius * dyN);   // N + 1px W
            TestNoInfluence(testObject, nbL, nbR, dxE, radius * dyN);   // N + 1px E
        }

#if false
        /// <summary>
        ///A test for PrepareInfluenceRegions (int)
        ///</summary>
        [DeploymentItem("SWA.Ariadne.Gui.Mazes.dll")]
        [TestMethod()]
        public void CI_PrepareInfluenceRegionsTest_03_BorderLimits()
        {
            string testObject = "borderLimits";
            int radius = SWA_Ariadne_Gui_Mazes_ContourImageAccessor.ContourDistance;
            int influenceRange = radius + 1;

            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.PrepareInfluenceRegions(influenceRange);

            // Verify that rx is always >= 0.
            for (int i = 0; i < 8; i++)
            {
                for (int j = 0; j < 8; j++)
                {
                    List<ContourImage.RelativePoint> list = SWA_Ariadne_Gui_Mazes_ContourImageAccessor.borderLimits[i, j];
                    foreach (ContourImage.RelativePoint pt in list)
                    {
                        Assert.IsTrue(pt.rx >= 0, testObject + " rx must be positive");
                    }
                }
            }
        }
#endif

#if false
        /// <summary>
        ///A test for PrepareInfluenceRegions (int)
        ///</summary>
        [DeploymentItem("SWA.Ariadne.Gui.Mazes.dll")]
        [TestMethod()]
        public void CI_PrepareInfluenceRegionsTest_04_ContourLimits()
        {
            string testObject = "contourLimits";
            int radius = SWA_Ariadne_Gui_Mazes_ContourImageAccessor.ContourDistance;
            int influenceRange = radius + 1;

            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.PrepareInfluenceRegions(influenceRange);

            // Verify that rx is always >= 0.
            for (int i = 0; i < 8; i++)
            {
                for (int j = 0; j < 8; j++)
                {
                    List<ContourImage.RelativePoint> list = SWA_Ariadne_Gui_Mazes_ContourImageAccessor.contourLimits[i, j];
                    foreach (ContourImage.RelativePoint pt in list)
                    {
                        Assert.IsTrue(pt.rx >= 0, testObject + " rx must be positive");
                    }
                }
            }
        }
#endif

#if false
        /// <summary>
        ///A test for PrepareInfluenceRegions (int)
        ///</summary>
        [DeploymentItem("SWA.Ariadne.Gui.Mazes.dll")]
        [TestMethod()]
        public void CI_PrepareInfluenceRegionsTest_05_BorderLimits()
        {
            string testObject = "borderLimits";
            int radius = SWA_Ariadne_Gui_Mazes_ContourImageAccessor.ContourDistance;
            int influenceRange = radius + 1;

            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.PrepareInfluenceRegions(influenceRange);

            // Verify that an application of the borderLimits gives the same scan lines as applying leftBorderLimits and rightBorderLimits.
            for (int i = 0; i < 8; i++)
            {
                for (int j = 0; j < 8; j++)
                {
                    #region Prepare required data structures.

                    int width = 2 * influenceRange + 1, height = 2 * influenceRange + 1;
                    int x = (width + 1) / 2, y = (height + 1) / 2;
                    List<int>[] objectXs, contourXs, borderXs;
                    List<int>[] objectXsLR, contourXsLR, borderXsLR;
                    SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InitializeScanLines(width, height, out objectXs, out contourXs, out borderXs);
                    SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InitializeScanLines(width, height, out objectXsLR, out contourXsLR, out borderXsLR);

                    #endregion

                    // Apply the (single) list to borderXs.
                    List<ContourImage.RelativePoint> list = SWA_Ariadne_Gui_Mazes_ContourImageAccessor.borderLimits[i, j];
                    foreach (ContourImage.RelativePoint rp in list)
                    {
                        SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y + rp.ry], x - rp.rx, x + rp.rx);
                    }

                    // Apply the left and right lists to borderXsLR.
                    list = SWA_Ariadne_Gui_Mazes_ContourImageAccessor.leftBorderLimits[i, j];
                    foreach (ContourImage.RelativePoint rp in list)
                    {
                        SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXsLR[y + rp.ry], x + rp.rx, x - rp.rx);
                    }
                    list = SWA_Ariadne_Gui_Mazes_ContourImageAccessor.rightBorderLimits[i, j];
                    foreach (ContourImage.RelativePoint rp in list)
                    {
                        SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXsLR[y + rp.ry], x - rp.rx, x + rp.rx);
                    }

                    // Compare the resulting scan lines.
                    for (y = 0; y < height; y++)
                    {
                        string testLine = testObject + string.Format("[{0},{1}][{2}]", i, j, y);
                        List<int> expected = borderXsLR[y], actual = borderXs[y];
                        Assert.AreEqual(expected.Count, actual.Count, testLine + " different count");

                        for (int p = 0; p < expected.Count; p++)
                        {
                            Assert.AreEqual(expected[p], actual[p], testLine + " different entry");
                        }
                    }
                }
            }
        }
#endif

        #endregion

        #region Unit tests for ScanObject()

        /// <summary>
        ///A test for ScanObject (Bitmap, int, int, Color, float, int[,], List&lt;int&gt;[])
        ///</summary>
        [DeploymentItem("SWA.Ariadne.Gui.Mazes.dll")]
        [TestMethod()]
        public void CI_ScanObjectTest_01_Rectangle()
        {
            string testObject = "ContourImage.ScanObject";

            Color backgroundColor = Color.Black;
            Color foregroundColor = Color.White;
            Brush fgBrush = new SolidBrush(foregroundColor);
            Pen fgPen = new Pen(fgBrush, 1);

            Bitmap image = new Bitmap(63, 63);
            Graphics g = Graphics.FromImage(image);
            g.FillRectangle(new SolidBrush(backgroundColor), 0, 0, image.Width, image.Height);

            // When painting into the image, leave an outer frame of 16 pixels free.

            int cx = (image.Width + 1) / 2, cy = (image.Height + 1) / 2;
            Rectangle rect = new Rectangle(cx - 8, cy - 4, 16, 8);
            g.FillRectangle(fgBrush, rect);
            testObject += "(Rectangle " + rect.ToString() + ")";

            TestScan(testObject, image, backgroundColor, 1);
        }

        /// <summary>
        ///A test for ScanObject (Bitmap, int, int, Color, float, int[,], List&lt;int&gt;[])
        ///</summary>
        [DeploymentItem("SWA.Ariadne.Gui.Mazes.dll")]
        [TestMethod()]
        public void CI_ScanObjectTest_02_Ellipse()
        {
            string testObject = "ContourImage.ScanObject";

            Color backgroundColor = Color.Black;
            Color foregroundColor = Color.White;
            Brush fgBrush = new SolidBrush(foregroundColor);
            Pen fgPen = new Pen(fgBrush, 1);

            Bitmap image = new Bitmap(63, 63);
            Graphics g = Graphics.FromImage(image);
            g.FillRectangle(new SolidBrush(backgroundColor), 0, 0, image.Width, image.Height);

            // When painting into the image, leave an outer frame of 16 pixels free.

            int cx = (image.Width + 1) / 2, cy = (image.Height + 1) / 2;
            Rectangle rect = new Rectangle(cx - 8, cy - 4, 16, 8);
            g.FillEllipse(fgBrush, rect);
            testObject += "(Ellipse " + rect.ToString() + ")";

            TestScan(testObject, image, backgroundColor, 1);
        }

        /// <summary>
        ///A test for ScanObject (Bitmap, int, int, Color, float, int[,], List&lt;int&gt;[])
        ///</summary>
        [DeploymentItem("SWA.Ariadne.Gui.Mazes.dll")]
        [TestMethod()]
        public void CI_ScanObjectTest_03_FlatDiamond()
        {
            string testObject = "ContourImage.ScanObject";

            Color backgroundColor = Color.Black;
            Color foregroundColor = Color.White;
            Brush fgBrush = new SolidBrush(foregroundColor);
            Pen fgPen = new Pen(fgBrush, 1);

            Bitmap image = new Bitmap(63, 63);
            Graphics g = Graphics.FromImage(image);
            g.FillRectangle(new SolidBrush(backgroundColor), 0, 0, image.Width, image.Height);

            // When painting into the image, leave an outer frame of 16 pixels free.

            int cx = (image.Width + 1) / 2, cy = (image.Height + 1) / 2;
            Rectangle rect = new Rectangle(cx - 12, cy - 4, 24, 8);
            Point pE = new Point(rect.Right - 1, (rect.Top + rect.Bottom) / 2);
            Point pN = new Point((rect.Left + rect.Right) / 2, rect.Top);
            Point pW = new Point(rect.Left, (rect.Top + rect.Bottom) / 2);
            Point pS = new Point((rect.Left + rect.Right) / 2, rect.Bottom - 1);
            g.FillPolygon(fgBrush, new Point[] { pE, pN, pW, pS });
            testObject += "(Diamond " + rect.ToString() + ")";

            TestScan(testObject, image, backgroundColor, 1);
        }

        /// <summary>
        ///A test for ScanObject (Bitmap, int, int, Color, float, int[,], List&lt;int&gt;[])
        ///</summary>
        [DeploymentItem("SWA.Ariadne.Gui.Mazes.dll")]
        [TestMethod()]
        public void CI_ScanObjectTest_04_SlimDiamond()
        {
            string testObject = "ContourImage.ScanObject";

            Color backgroundColor = Color.Black;
            Color foregroundColor = Color.White;
            Brush fgBrush = new SolidBrush(foregroundColor);
            Pen fgPen = new Pen(fgBrush, 1);

            Bitmap image = new Bitmap(63, 63);
            Graphics g = Graphics.FromImage(image);
            g.FillRectangle(new SolidBrush(backgroundColor), 0, 0, image.Width, image.Height);

            // When painting into the image, leave an outer frame of 16 pixels free.

            int cx = (image.Width + 1) / 2, cy = (image.Height + 1) / 2;
            Rectangle rect = new Rectangle(cx - 4, cy - 12, 8, 24);
            Point pE = new Point(rect.Right - 1, (rect.Top + rect.Bottom) / 2);
            Point pN = new Point((rect.Left + rect.Right) / 2, rect.Top);
            Point pW = new Point(rect.Left, (rect.Top + rect.Bottom) / 2);
            Point pS = new Point((rect.Left + rect.Right) / 2, rect.Bottom - 1);
            g.FillPolygon(fgBrush, new Point[] { pE, pN, pW, pS });
            testObject += "(Diamond " + rect.ToString() + ")";

            TestScan(testObject, image, backgroundColor, 1);
        }

        /// <summary>
        ///A test for ScanObject (Bitmap, int, int, Color, float, int[,], List&lt;int&gt;[])
        ///</summary>
        [DeploymentItem("SWA.Ariadne.Gui.Mazes.dll")]
        [TestMethod()]
        public void CI_ScanObjectTest_05_VerticalLine()
        {
            string testObject = "ContourImage.ScanObject";

            Color backgroundColor = Color.Black;
            Color foregroundColor = Color.White;
            Brush fgBrush = new SolidBrush(foregroundColor);
            Pen fgPen = new Pen(fgBrush, 1);

            Bitmap image = new Bitmap(63, 63);
            Graphics g = Graphics.FromImage(image);
            g.FillRectangle(new SolidBrush(backgroundColor), 0, 0, image.Width, image.Height);

            // When painting into the image, leave an outer frame of 16 pixels free.

            int cx = (image.Width + 1) / 2, cy = (image.Height + 1) / 2;
            Rectangle rect = new Rectangle(cx - 8, cy - 4, 16, 8);
            Point pE = new Point(rect.Right - 1, (rect.Top + rect.Bottom) / 2);
            Point pN = new Point((rect.Left + rect.Right) / 2, rect.Top);
            Point pW = new Point(rect.Left, (rect.Top + rect.Bottom) / 2);
            Point pS = new Point((rect.Left + rect.Right) / 2, rect.Bottom - 1);
            g.DrawLine(fgPen, pN, pS);

            testObject += "(VerticalLine " + pN.ToString() + "-" + pS.ToString() + ")";

            TestScan(testObject, image, backgroundColor, 1);
        }

        /// <summary>
        ///A test for ScanObject (Bitmap, int, int, Color, float, int[,], List&lt;int&gt;[])
        ///</summary>
        [DeploymentItem("SWA.Ariadne.Gui.Mazes.dll")]
        [TestMethod()]
        public void CI_ScanObjectTest_06_HorizontalLine()
        {
            string testObject = "ContourImage.ScanObject";

            Color backgroundColor = Color.Black;
            Color foregroundColor = Color.White;
            Brush fgBrush = new SolidBrush(foregroundColor);
            Pen fgPen = new Pen(fgBrush, 1);

            Bitmap image = new Bitmap(63, 63);
            Graphics g = Graphics.FromImage(image);
            g.FillRectangle(new SolidBrush(backgroundColor), 0, 0, image.Width, image.Height);

            // When painting into the image, leave an outer frame of 16 pixels free.

            int cx = (image.Width + 1) / 2, cy = (image.Height + 1) / 2;
            Rectangle rect = new Rectangle(cx - 8, cy - 4, 16, 8);
            Point pE = new Point(rect.Right - 1, (rect.Top + rect.Bottom) / 2);
            Point pN = new Point((rect.Left + rect.Right) / 2, rect.Top);
            Point pW = new Point(rect.Left, (rect.Top + rect.Bottom) / 2);
            Point pS = new Point((rect.Left + rect.Right) / 2, rect.Bottom - 1);
            g.DrawLine(fgPen, pW, pE);

            testObject += "(HorizontalLine " + pW.ToString() + "-" + pE.ToString() + ")";

            TestScan(testObject, image, backgroundColor, 1);
        }

        /// <summary>
        ///A test for ScanObject (Bitmap, int, int, Color, float, int[,], List&lt;int&gt;[])
        ///</summary>
        [DeploymentItem("SWA.Ariadne.Gui.Mazes.dll")]
        [TestMethod()]
        public void CI_ScanObjectTest_07_UprightCross()
        {
            string testObject = "ContourImage.ScanObject";

            Color backgroundColor = Color.Black;
            Color foregroundColor = Color.White;
            Brush fgBrush = new SolidBrush(foregroundColor);
            Pen fgPen = new Pen(fgBrush, 1);

            Bitmap image = new Bitmap(63, 63);
            Graphics g = Graphics.FromImage(image);
            g.FillRectangle(new SolidBrush(backgroundColor), 0, 0, image.Width, image.Height);

            // When painting into the image, leave an outer frame of 16 pixels free.

            int cx = (image.Width + 1) / 2, cy = (image.Height + 1) / 2;
            Rectangle rect = new Rectangle(cx - 8, cy - 4, 16, 8);
            Point pE = new Point(rect.Right - 1, (rect.Top + rect.Bottom) / 2);
            Point pN = new Point((rect.Left + rect.Right) / 2, rect.Top);
            Point pW = new Point(rect.Left, (rect.Top + rect.Bottom) / 2);
            Point pS = new Point((rect.Left + rect.Right) / 2, rect.Bottom - 1);
            g.DrawLine(fgPen, pN, pS);
            g.DrawLine(fgPen, pW, pE);

            testObject += "(UprightCross " + rect.ToString() + ")";

            TestScan(testObject, image, backgroundColor, 1);
        }

        /// <summary>
        ///A test for ScanObject (Bitmap, int, int, Color, float, int[,], List&lt;int&gt;[])
        ///</summary>
        [DeploymentItem("SWA.Ariadne.Gui.Mazes.dll")]
        [TestMethod()]
        public void CI_ScanObjectTest_08_FlatDiagonalCross()
        {
            string testObject = "ContourImage.ScanObject";

            Color backgroundColor = Color.Black;
            Color foregroundColor = Color.White;
            Brush fgBrush = new SolidBrush(foregroundColor);
            Pen fgPen = new Pen(fgBrush, 1);

            Bitmap image = new Bitmap(63, 63);
            Graphics g = Graphics.FromImage(image);
            g.FillRectangle(new SolidBrush(backgroundColor), 0, 0, image.Width, image.Height);

            // When painting into the image, leave an outer frame of 16 pixels free.

            int cx = (image.Width + 1) / 2, cy = (image.Height + 1) / 2;
            Rectangle rect = new Rectangle(cx - 8, cy - 4, 16, 8);
            Point pE = new Point(rect.Right - 1, (rect.Top + rect.Bottom) / 2);
            Point pN = new Point((rect.Left + rect.Right) / 2, rect.Top);
            Point pW = new Point(rect.Left, (rect.Top + rect.Bottom) / 2);
            Point pS = new Point((rect.Left + rect.Right) / 2, rect.Bottom - 1);
            Point pNW = new Point(rect.Left, rect.Top);
            Point pNE = new Point(rect.Right - 1, rect.Top);
            Point pSW = new Point(rect.Left, rect.Bottom - 1);
            Point pSE = new Point(rect.Right - 1, rect.Bottom - 1);
            g.DrawLine(fgPen, pNE, pSW);
            g.DrawLine(fgPen, pNW, pSE);

            testObject += "(DiagonalCross " + rect.ToString() + ")";

            TestScan(testObject, image, backgroundColor, 2);
        }

        /// <summary>
        ///A test for ScanObject (Bitmap, int, int, Color, float, int[,], List&lt;int&gt;[])
        ///</summary>
        [DeploymentItem("SWA.Ariadne.Gui.Mazes.dll")]
        [TestMethod()]
        public void CI_ScanObjectTest_09_SlimDiagonalCross()
        {
            string testObject = "ContourImage.ScanObject";

            Color backgroundColor = Color.Black;
            Color foregroundColor = Color.White;
            Brush fgBrush = new SolidBrush(foregroundColor);
            Pen fgPen = new Pen(fgBrush, 1);

            Bitmap image = new Bitmap(63, 63);
            Graphics g = Graphics.FromImage(image);
            g.FillRectangle(new SolidBrush(backgroundColor), 0, 0, image.Width, image.Height);

            // When painting into the image, leave an outer frame of 16 pixels free.

            int cx = (image.Width + 1) / 2, cy = (image.Height + 1) / 2;
            Rectangle rect = new Rectangle(cx - 4, cy - 8, 8, 16);
            Point pE = new Point(rect.Right - 1, (rect.Top + rect.Bottom) / 2);
            Point pN = new Point((rect.Left + rect.Right) / 2, rect.Top);
            Point pW = new Point(rect.Left, (rect.Top + rect.Bottom) / 2);
            Point pS = new Point((rect.Left + rect.Right) / 2, rect.Bottom - 1);
            Point pNW = new Point(rect.Left, rect.Top);
            Point pNE = new Point(rect.Right - 1, rect.Top);
            Point pSW = new Point(rect.Left, rect.Bottom - 1);
            Point pSE = new Point(rect.Right - 1, rect.Bottom - 1);
            g.DrawLine(fgPen, pNE, pSW);
            g.DrawLine(fgPen, pNW, pSE);

            testObject += "(DiagonalCross " + rect.ToString() + ")";

            TestScan(testObject, image, backgroundColor, 2);
        }

        /// <summary>
        ///A test for ScanObject (Bitmap, int, int, Color, float, int[,], List&lt;int&gt;[])
        ///</summary>
        [DeploymentItem("SWA.Ariadne.Gui.Mazes.dll")]
        [TestMethod()]
        public void CI_ScanObjectTest_10_LargeCircle()
        {
            string testObject = "ContourImage.ScanObject";

            Color backgroundColor = Color.Black;
            Color foregroundColor = Color.White;
            Brush fgBrush = new SolidBrush(foregroundColor);
            Pen fgPen = new Pen(fgBrush, 1);

            Bitmap image = new Bitmap(120, 120);
            Graphics g = Graphics.FromImage(image);
            g.FillRectangle(new SolidBrush(backgroundColor), 0, 0, image.Width, image.Height);

            // When painting into the image, leave an outer frame of 16 pixels free.

            int cx = (image.Width + 1) / 2, cy = (image.Height + 1) / 2;
            Rectangle rect = new Rectangle(cx - 40, cy - 40, 80, 80);
            g.FillEllipse(fgBrush, rect);
            testObject += "(Circle " + rect.ToString() + ")";

            TestScan(testObject, image, backgroundColor, 1);
        }

        #endregion

        #region Unit tests for InsertPair()

        /// <summary>
        ///A test for InsertPair ()
        ///</summary>
        [DeploymentItem("SWA.Ariadne.Gui.Mazes.dll")]
        [TestMethod()]
        public void CI_InsertPairTest_01()
        {
            string testObject = "InsertPair";

            // Prepare data structures used in the test.
            int width = 1000, height = 1;
            List<int>[] objectXs, contourXs, borderXs;
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InitializeScanLines(width, height, out objectXs, out contourXs, out borderXs);
            List<int> borderX = borderXs[0];

            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderX, 100, 900);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderX, 200, 800);

            int[] expectedPoints = { 100, 900 };
            TestInsertPair(testObject, borderXs, expectedPoints);
        }

        /// <summary>
        ///A test for InsertPair ()
        ///</summary>
        [DeploymentItem("SWA.Ariadne.Gui.Mazes.dll")]
        [TestMethod()]
        public void CI_InsertPairTest_02()
        {
            string testObject = "InsertPair";

            // Prepare data structures used in the test.
            int width = 1000, height = 1;
            List<int>[] objectXs, contourXs, borderXs;
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InitializeScanLines(width, height, out objectXs, out contourXs, out borderXs);
            List<int> borderX = borderXs[0];

            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderX, 100, 300);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderX, 500, 700);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderX, 700, 900);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderX, 300, 500);

            int[] expectedPoints = { 100, 900 };
            TestInsertPair(testObject, borderXs, expectedPoints);
        }

        /// <summary>
        ///A test for InsertPair ()
        ///</summary>
        [DeploymentItem("SWA.Ariadne.Gui.Mazes.dll")]
        [TestMethod()]
        public void CI_InsertPairTest_03()
        {
            string testObject = "InsertPair";

            // Prepare data structures used in the test.
            int width = 1000, height = 1;
            List<int>[] objectXs, contourXs, borderXs;
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InitializeScanLines(width, height, out objectXs, out contourXs, out borderXs);
            List<int> borderX = borderXs[0];

            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderX, 100, 400);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderX, 500, 900);

            int[] expectedPoints = { 100, 400, 500, 900 };
            TestInsertPair(testObject, borderXs, expectedPoints);
        }

        /// <summary>
        ///A test for InsertPair ()
        ///</summary>
        [DeploymentItem("SWA.Ariadne.Gui.Mazes.dll")]
        [TestMethod()]
        public void CI_InsertPairTest_04()
        {
            string testObject = "InsertPair";

            // Prepare data structures used in the test.
            int width = 1000, height = 1;
            List<int>[] objectXs, contourXs, borderXs;
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InitializeScanLines(width, height, out objectXs, out contourXs, out borderXs);
            List<int> borderX = borderXs[0];

            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderX, 100, 300);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderX, 500, 700);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderX, 700, 900);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderX, 300, 500);

            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderX, 100, 900);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderX, 400, 600);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderX, 600, 800);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderX, 400, 800);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderX, 550, 850);

            int[] expectedPoints = { 100, 900 };
            TestInsertPair(testObject, borderXs, expectedPoints);
        }

        /// <summary>
        ///A test for InsertPair ()
        ///</summary>
        [DeploymentItem("SWA.Ariadne.Gui.Mazes.dll")]
        [TestMethod()]
        public void CI_InsertPairTest_05()
        {
            string testObject = "InsertPair";

            // Prepare data structures used in the test.
            int width = 1000, height = 1;
            List<int>[] objectXs, contourXs, borderXs;
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InitializeScanLines(width, height, out objectXs, out contourXs, out borderXs);
            List<int> borderX = borderXs[0];

            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderX, 100, 300);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderX, 301, 500);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderX, 501, 900);

            int[] expectedPoints = { 100, 900 };
            TestInsertPair(testObject, borderXs, expectedPoints);
        }

        /// <summary>
        ///A test for InsertPair ()
        ///</summary>
        [DeploymentItem("SWA.Ariadne.Gui.Mazes.dll")]
        [TestMethod()]
        public void CI_InsertPairTest_06()
        {
            string testObject = "InsertPair";

            // Prepare data structures used in the test.
            int width = 1000, height = 1;
            List<int>[] objectXs, contourXs, borderXs;
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InitializeScanLines(width, height, out objectXs, out contourXs, out borderXs);
            List<int> borderX = borderXs[0];

            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderX, 501, 900);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderX, 301, 500);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderX, 100, 300);

            int[] expectedPoints = { 100, 900 };
            TestInsertPair(testObject, borderXs, expectedPoints);
        }

        /// <summary>
        ///A test for InsertPair ()
        ///</summary>
        [DeploymentItem("SWA.Ariadne.Gui.Mazes.dll")]
        [TestMethod()]
        public void CI_InsertPairTest_07()
        {
            string testObject = "InsertPair";

            // Prepare data structures used in the test.
            int width = 1000, height = 1;
            List<int>[] objectXs, contourXs, borderXs;
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InitializeScanLines(width, height, out objectXs, out contourXs, out borderXs);
            List<int> borderX = borderXs[0];

            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderX, 100, 300);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderX, 501, 900);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderX, 301, 500);

            int[] expectedPoints = { 100, 900 };
            TestInsertPair(testObject, borderXs, expectedPoints);
        }

        /// <summary>
        ///A test for InsertPair ()
        ///</summary>
        [DeploymentItem("SWA.Ariadne.Gui.Mazes.dll")]
        [TestMethod()]
        public void CI_InsertPairTest_08_ThickLines()
        {
            string testObject = "ContourImage.ScanObject";

            Color backgroundColor = Color.White;
            Color foregroundColor = Color.Black;
            Brush fgBrush = new SolidBrush(foregroundColor);
            Pen fgPen = new Pen(fgBrush, 8);
            fgPen.StartCap = fgPen.EndCap = System.Drawing.Drawing2D.LineCap.Round;

            // When painting into the image, leave an outer frame of 16 pixels free.
            // Only use the range 50..250.
            int width = 300, height = 300;
            Bitmap image = new Bitmap(width, height);
            Graphics g = Graphics.FromImage(image);

            int contourDist = SWA_Ariadne_Gui_Mazes_ContourImageAccessor.ContourDistance;
            int blurDist = SWA_Ariadne_Gui_Mazes_ContourImageAccessor.GetBlurDistance(backgroundColor);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.PrepareInfluenceRegions(contourDist + blurDist);

            int[,] dist2ToImage;
            List<int>[] objectXs, contourXs, borderXs;
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InitializeDist2ToImage(image.Width, image.Height, out dist2ToImage);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InitializeScanLines(width, height, out objectXs, out contourXs, out borderXs);

            #region Create a complicated pattern of border scan lines.

            float fuzziness = 0.1F;
            Point[] points = {
                new Point(50, 50), new Point(250, 250),
                new Point(200, 100), new Point(100, 200),
            };

            g.FillRectangle(new SolidBrush(backgroundColor), 0, 0, image.Width, image.Height);

            for (int i = 0, j = i + 1; j < points.Length; i++, j++)
            {
                g.DrawLine(fgPen, points[i], points[j]);

                int y0 = (points[i].Y + points[j].Y) / 2;
                #region Find the leftmost object pixel on the scan line at y0.

                int x0 = 0;
                while (SWA_Ariadne_Gui_Mazes_ContourImageAccessor.ColorDistance(image.GetPixel(x0, y0), backgroundColor) <= fuzziness)
                {
                    x0++;
                }

                #endregion

                SWA_Ariadne_Gui_Mazes_ContourImageAccessor.ScanObject(image, x0, y0, backgroundColor, fuzziness, dist2ToImage, objectXs, contourXs, borderXs);
            }

            #endregion

            TestBorderScanlines(testObject, borderXs);
        }
        #endregion

        #region Unit tests for EliminateInsideRegions()

        /// <summary>
        ///A test for EliminateInsideRegions (List&lt;int&gt;[], List&lt;bool&gt;[], int, int)
        ///</summary>
        [DeploymentItem("SWA.Ariadne.Gui.Mazes.dll")]
        [TestMethod()]
        public void CI_EliminateInsideRegionsTest_01()
        {
            string testObject = "EliminateInsideRegions";

            int width = 11, height = 10, sy = 1, y0 = sy - 1;
            List<int>[] objectXs, contourXs, borderXs;
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InitializeScanLines(width, height, out objectXs, out contourXs, out borderXs);

            int y = y0;
            // nothing

            y += sy;
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 4, 6);

            y += sy;
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 2, 7);

            y += sy;
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 1, 2);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 4, 5);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 7, 8);

            y += sy;
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 1, 2);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 8, 9);

            y += sy;
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 1, 2);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 4, 4);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 7, 8);

            int insideRegionsExpected = 0;
            int insideRegionsActual = SWA_Ariadne_Gui_Mazes_ContourImageAccessor.EliminateInsideRegions(borderXs, y0, sy);

            Assert.AreEqual(insideRegionsExpected, insideRegionsActual, testObject + " returned wrong number of inside regions");
        }

        /// <summary>
        ///A test for EliminateInsideRegions (List&lt;int&gt;[], List&lt;bool&gt;[], int, int)
        ///</summary>
        [DeploymentItem("SWA.Ariadne.Gui.Mazes.dll")]
        [TestMethod()]
        public void CI_EliminateInsideRegionsTest_02()
        {
            string testObject = "EliminateInsideRegions";

            int width = 11, height = 10, sy = 1, y0 = sy - 1;
            List<int>[] objectXs, contourXs, borderXs;
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InitializeScanLines(width, height, out objectXs, out contourXs, out borderXs);

            int y = y0;
            // nothing

            y += sy;
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 4, 6);

            y += sy;
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 2, 7);

            y += sy;
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 1, 2);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 4, 5);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 7, 8);

            y += sy;
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 1, 2);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 8, 9);

            y += sy;
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 1, 2);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 4, 4);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 7, 8);

            y += sy;
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 2, 7);

            int insideRegionsExpected = 1;
            int insideRegionsActual = SWA_Ariadne_Gui_Mazes_ContourImageAccessor.EliminateInsideRegions(borderXs, y0, sy);

            Assert.AreEqual(insideRegionsExpected, insideRegionsActual, testObject + " returned wrong number of inside regions");
        }

        /// <summary>
        ///A test for EliminateInsideRegions (List&lt;int&gt;[], List&lt;bool&gt;[], int, int)
        ///</summary>
        [DeploymentItem("SWA.Ariadne.Gui.Mazes.dll")]
        [TestMethod()]
        public void CI_EliminateInsideRegionsTest_03()
        {
            string testObject = "EliminateInsideRegions";

            int width = 11, height = 10, sy = 1, y0 = sy - 1;
            List<int>[] objectXs, contourXs, borderXs;
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InitializeScanLines(width, height, out objectXs, out contourXs, out borderXs);

            int y = y0;
            // nothing

            y += sy;
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 4, 6);

            y += sy;
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 2, 7);

            y += sy;
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 1, 2);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 4, 5);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 7, 8);

            y += sy;
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 1, 2);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 4, 5);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 8, 9);

            y += sy;
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 1, 2);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 4, 4);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 7, 8);

            y += sy;
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderXs[y], 2, 7);

            int insideRegionsExpected = 2;
            int insideRegionsActual = SWA_Ariadne_Gui_Mazes_ContourImageAccessor.EliminateInsideRegions(borderXs, y0, sy);

            Assert.AreEqual(insideRegionsExpected, insideRegionsActual, testObject + " returned wrong number of inside regions");
        }

        #endregion

        #endregion

        #region Auxiliary methods

        private static void TestInfluence(string testObject, int nbL, int nbR, int x, int y, int btExpected)
        {
            testObject += string.Format("<{0},{1}>: [{2},{3}]", nbL, nbR, x, y);
            int d2 = SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InfluenceD2(nbL, nbR, x, y);

            Assert.IsTrue(d2 < int.MaxValue, testObject + " should be influenced");
            Assert.AreEqual(x * x + y * y, d2, testObject + " is not correct");

#if false
            int btActual = SWA_Ariadne_Gui_Mazes_ContourImageAccessor.BorderLimitType(nbL, nbR, x, y);
            Assert.AreEqual(btExpected, btActual, testObject + " has the wrong border type");
#endif
        }

        private static void TestNoInfluence(string testObject, int nbL, int nbR, int x, int y)
        {
            testObject += string.Format("<{0},{1}>: [{2},{3}]", nbL, nbR, x, y);
            int d2 = SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InfluenceD2(nbL, nbR, x, y);

            Assert.IsFalse(d2 < int.MaxValue, testObject + " should not be influence");
        }

        private static void TestScan(string testObject, Bitmap image, Color backgroundColor, int maxContourScanRegions)
        {
            for (int y = 0; y < image.Height; y++)
            {
                TestScan(testObject, image, backgroundColor, y, maxContourScanRegions);
            }
        }

        private static void TestScan(string testObject, Bitmap image, Color backgroundColor, int y0, int maxContourScanRegions)
        {
            testObject += " @ " + y0.ToString();
            float fuzziness = 0.1F;

            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.PrepareInfluenceRegions(SWA_Ariadne_Gui_Mazes_ContourImageAccessor.GetFrameWidth(backgroundColor));

            #region Find the leftmost object pixel on the scan line at y0.

            int x0 = 0;
            while (SWA_Ariadne_Gui_Mazes_ContourImageAccessor.ColorDistance(image.GetPixel(x0, y0), backgroundColor) <= fuzziness)
            {
                x0++;
                if (x0 >= image.Width)
                {
                    return;
                }
            }

            #endregion

            #region Prepare required data structures.

            int width = image.Width, height = image.Height;
            int[,] dist2ToImage;
            List<int>[] objectXs, contourXs, borderXs;
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InitializeDist2ToImage(width, height, out dist2ToImage);
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InitializeScanLines(width, height, out objectXs, out contourXs, out borderXs);

            #endregion

            bool found = SWA_Ariadne_Gui_Mazes_ContourImageAccessor.ScanObject(image, x0, y0, backgroundColor, fuzziness, dist2ToImage, objectXs, contourXs, borderXs);

            #region Test if the object map is well formed.
            for (int i = 0; i < height; i++)
            {
                int nEntries = objectXs[i].Count;
                int m = nEntries % 2;
                Assert.AreEqual(1, m, testObject + string.Format(" - objectXs[{0}] must be an odd number: {1}", i, nEntries));

                int nRegions = (nEntries - 1) / 2;
                Assert.IsTrue(nRegions <= maxContourScanRegions, testObject + string.Format(" - objectXs[{0}] regions = {1} must be less than {2}", i, nRegions, maxContourScanRegions));
            }
            #endregion

            #region Test if the object map is complete.
            int imageArea = ImageArea(image, backgroundColor, fuzziness);
            int objectArea = ObjectArea(objectXs);
            Assert.AreEqual(imageArea, objectArea, testObject + string.Format(" - object area and image area must be equal"));
            #endregion

            // Test if the contour map is well formed.
            TestBorderScanlines(testObject + " - contourXs", contourXs);

            // Test if the border map is well formed.
            TestBorderScanlines(testObject + " - borderXs", borderXs);
        }

        private static int ImageArea(Bitmap image, Color backgroundColor, float fuzziness)
        {
            int result = 0;

            for (int y = 0; y < image.Height; y++)
            {
                for (int x = 0; x < image.Width; x++)
                {
                    if (Math.Abs(image.GetPixel(x, y).GetBrightness() - backgroundColor.GetBrightness()) > fuzziness)
                    {
                        result++;
                    }
                }
            }

            return result;
        }

        private static int ObjectArea(List<int>[] objectXs)
        {
            int result = 0;

            for (int i = 0; i < objectXs.Length; i++)
            {
                for (int p = 0; p + 1 < objectXs[i].Count; p += 2)
                {
                    int w = objectXs[i][p + 1] - objectXs[i][p] + 1;
                    result += w;
                }
            }

            return result;
        }

        private static void InsertBorderLR(List<int> borderX, List<bool> borderLR, int left, int right)
        {
            SWA_Ariadne_Gui_Mazes_ContourImageAccessor.InsertPair(borderX, left, right);
        }

        private static void TestInsertPair(string testObject, List<int>[] borderXs, int[] expectedPoints)
        {
            Assert.AreEqual(expectedPoints.Length + 2, borderXs[0].Count, testObject + " left a wrong number of points");
            for (int i = 0; i < expectedPoints.Length; i++)
            {
                Assert.AreEqual(expectedPoints[i], borderXs[0][i + 1], testObject + string.Format(" left a wrong entry at [{0}]", i + 1));
            }
        }

        private static void TestBorderScanlines(string testObject, List<int>[] borderXs)
        {
            int height = borderXs.Length;

            for (int i = 0; i < height; i++)
            {
                string testLine = testObject + string.Format("[{0}]", i);

                int nEntries = borderXs[i].Count;
                int m = nEntries % 2;
                Assert.AreEqual(0, m, testLine + string.Format(" must be an even number: {0}", nEntries));

                for (int p = 0; p < nEntries - 1; p++)
                {
                    int q = p + 1;
                    int xp = borderXs[i][p], xq = borderXs[i][q];
                    Assert.IsTrue(xp <= xq, testLine + string.Format(" must be sorted: [{0}] = {1}, [{2}] = {3}", p, xp, q, xq));
#if false
                    Assert.IsTrue(xp <  xq, testLine + string.Format(" must be unique: [{0}] = {1}, [{2}] = {3}", p, xp, q, xq));
#endif
                }
            }
        }

        #endregion
    }
}
